/**
 * Recipe Database for Smart Global Limited
 * Products featured: Kent Boringer, SPUDS chips, Ice Cream Toppings, Crepes Mix
 *
 * Ready for backend integration - just replace with API calls
 */

export const recipesData = [
  {
    id: 1,
    slug: "fluffy-kent-boringer-pancakes",
    title: "Fluffy Kent Boringer Pancakes with Fresh Berries",
    category: "Breakfast",
    image: "top2", // from assets
    cookTime: "15 min",
    prepTime: "10 min",
    totalTime: "25 min",
    servings: 4,
    difficulty: "Easy",
    rating: 4.8,
    reviews: 24,
    author: {
      name: "Smart Global Team",
      avatar: "SG",
      bio: "Professional chefs and food developers",
    },
    date: "1 week ago",
    views: 342,
    lastUpdated: "January 28, 2025",
    description:
      "Start your morning with these incredibly fluffy pancakes made with Kent Boringer premium pancake mix. The secret to their light, airy texture is in the quality ingredients and our proven technique. Perfect for family breakfasts or weekend brunch gatherings.",
    ingredients: [
      "2 cups Kent Boringer Pancake Mix",
      "1½ cups whole milk (or buttermilk for extra fluff)",
      "2 large eggs, room temperature",
      "3 tablespoons melted butter, plus extra for cooking",
      "1 teaspoon vanilla extract",
      "1 cup fresh mixed berries (strawberries, blueberries, raspberries)",
      "Maple syrup for serving",
      "Powdered sugar for dusting (optional)",
    ],
    directions: [
      "In a large mixing bowl, whisk together the Kent Boringer Pancake Mix and set aside.",
      "In a separate bowl, beat the eggs lightly, then add milk, melted butter, and vanilla extract. Mix until well combined.",
      "Pour the wet ingredients into the dry ingredients. Gently fold together until just combined - don't overmix! A few lumps are perfectly fine and will result in fluffier pancakes.",
      "Let the batter rest for 5 minutes. This allows the Kent Boringer mix to properly hydrate and creates those signature air pockets.",
      "Heat a non-stick griddle or large skillet over medium heat. Brush lightly with butter.",
      "Pour ¼ cup of batter for each pancake onto the griddle. Cook until bubbles form on the surface and edges look set, about 2-3 minutes.",
      "Flip carefully and cook for another 1-2 minutes until golden brown.",
      "Stack pancakes on serving plates, top with fresh berries, drizzle with maple syrup, and dust with powdered sugar if desired.",
    ],
    tips: [
      "Don't overmix the batter - lumps are your friend for fluffy pancakes!",
      "Room temperature ingredients mix better and create a smoother batter.",
      "Keep cooked pancakes warm in a 200°F oven while you finish the batch.",
      "For extra indulgence, add chocolate chips or sliced bananas to the batter.",
    ],
    nutrition: {
      calories: 320,
      protein: "8g",
      carbs: "45g",
      fat: "12g",
      fiber: "2g",
    },
    tags: ["breakfast", "pancakes", "brunch", "family-friendly", "quick"],
    featured: true,
  },
  {
    id: 2,
    slug: "creamy-vegetable-soup",
    title: "Creamy Vegetable Soup - Restaurant Style",
    category: "Soups",
    image: "kent",
    cookTime: "25 min",
    prepTime: "15 min",
    totalTime: "40 min",
    servings: 6,
    difficulty: "Easy",
    rating: 4.9,
    reviews: 31,
    author: {
      name: "Smart Global Team",
      avatar: "SG",
      bio: "Professional chefs and food developers",
    },
    date: "2 weeks ago",
    views: 428,
    lastUpdated: "January 20, 2025",
    description:
      "This velvety smooth vegetable soup is comfort in a bowl. Made with fresh seasonal vegetables and finished with a touch of cream, it's perfect for chilly evenings or as an elegant starter for dinner parties. The secret is roasting the vegetables first for deeper flavor.",
    ingredients: [
      "2 tablespoons olive oil",
      "1 large onion, diced",
      "3 cloves garlic, minced",
      "3 medium carrots, peeled and chopped",
      "2 stalks celery, chopped",
      "1 medium potato, peeled and cubed",
      "1 cup broccoli florets",
      "4 cups vegetable broth",
      "1 bay leaf",
      "½ cup heavy cream",
      "Salt and black pepper to taste",
      "Fresh thyme for garnish",
      "Crusty bread for serving",
    ],
    directions: [
      "Heat olive oil in a large pot over medium heat. Add diced onion and sauté until translucent, about 5 minutes.",
      "Add minced garlic and cook for another minute until fragrant.",
      "Add carrots, celery, and potato. Stir and cook for 5 minutes to slightly soften the vegetables.",
      "Pour in the vegetable broth and add the bay leaf. Bring to a boil, then reduce heat and simmer for 15 minutes.",
      "Add broccoli florets and continue simmering for another 5-7 minutes until all vegetables are tender.",
      "Remove the bay leaf. Use an immersion blender to puree the soup until smooth and creamy. Alternatively, carefully transfer to a blender in batches.",
      "Stir in heavy cream and season with salt and pepper to taste. Heat through but don't boil.",
      "Serve hot, garnished with fresh thyme leaves and alongside crusty bread.",
    ],
    tips: [
      "For a vegan version, substitute heavy cream with coconut cream or cashew cream.",
      "Roast the vegetables at 400°F for 20 minutes before adding to the pot for extra depth of flavor.",
      "This soup freezes beautifully - make a double batch!",
      "Add a pinch of nutmeg for a warming, subtle spice note.",
    ],
    nutrition: {
      calories: 185,
      protein: "4g",
      carbs: "18g",
      fat: "11g",
      fiber: "4g",
    },
    tags: ["soup", "vegetarian", "comfort-food", "healthy", "winter"],
    featured: false,
  },
  {
    id: 3,
    slug: "gourmet-pancake-dessert-tower",
    title: "Gourmet Pancake Dessert Tower with Raspberry Topping",
    category: "Desserts",
    image: "topping",
    cookTime: "30 min",
    prepTime: "20 min",
    totalTime: "50 min",
    servings: 4,
    difficulty: "Medium",
    rating: 5.0,
    reviews: 18,
    author: {
      name: "Smart Global Team",
      avatar: "SG",
      bio: "Professional chefs and food developers",
    },
    date: "1 month ago",
    views: 567,
    lastUpdated: "January 5, 2025",
    description:
      "Transform your pancakes into an impressive dessert masterpiece! This elegant tower features layers of fluffy Kent Boringer pancakes stacked with whipped cream and finished with our premium Kent Raspberry Topping. It's a showstopper that's surprisingly easy to make.",
    ingredients: [
      "1 batch Kent Boringer Pancakes (about 12 small pancakes)",
      "1 cup heavy whipping cream",
      "3 tablespoons powdered sugar",
      "1 teaspoon vanilla extract",
      "1 jar Kent Raspberry Topping (Premium Ice Cream Topping)",
      "Fresh raspberries for garnish",
      "Mint leaves for decoration",
      "White chocolate shavings (optional)",
      "Edible gold dust for extra elegance (optional)",
    ],
    directions: [
      "Prepare Kent Boringer pancakes according to package directions, making them slightly smaller than usual (about 3 inches diameter). Let cool completely.",
      "In a chilled bowl, whip the heavy cream with powdered sugar and vanilla extract until stiff peaks form. Keep refrigerated.",
      "To assemble each tower: Place one pancake on a serving plate as the base.",
      "Spread a thin layer of whipped cream on top, then add a small spoonful of Kent Raspberry Topping.",
      "Add another pancake and repeat the layering process. Continue until you have 3-4 pancakes per tower.",
      "Top the final pancake with a generous dollop of whipped cream.",
      "Drizzle Kent Raspberry Topping over the entire tower, letting it cascade down the sides.",
      "Garnish with fresh raspberries, mint leaves, and white chocolate shavings.",
      "For special occasions, add a light dusting of edible gold dust. Serve immediately.",
    ],
    tips: [
      "Make pancakes ahead and store in the refrigerator for easier assembly.",
      "Chill your mixing bowl and beaters for 15 minutes before whipping cream for best results.",
      "Use a piping bag with a star tip for more professional-looking cream layers.",
      "Don't stack too high - 3-4 pancakes is the sweet spot for stability and eating.",
    ],
    nutrition: {
      calories: 485,
      protein: "7g",
      carbs: "58g",
      fat: "24g",
      fiber: "3g",
    },
    tags: ["dessert", "special-occasion", "raspberry", "elegant", "pancakes"],
    featured: true,
  },
  {
    id: 4,
    slug: "spuds-loaded-nachos-supreme",
    title: "SPUDS Chips Loaded Nachos Supreme",
    category: "Snacks",
    image: "spuds",
    cookTime: "20 min",
    prepTime: "15 min",
    totalTime: "35 min",
    servings: 4,
    difficulty: "Easy",
    rating: 4.7,
    reviews: 42,
    author: {
      name: "Smart Global Team",
      avatar: "SG",
      bio: "Professional chefs and food developers",
    },
    date: "3 weeks ago",
    views: 612,
    lastUpdated: "January 15, 2025",
    description:
      "Upgrade your snack game with these incredible loaded nachos made with crispy SPUDS potato chips! Layers of crunchy chips, melted cheese, seasoned ground beef, and all your favorite toppings create the ultimate party food or game-day treat.",
    ingredients: [
      "1 large bag SPUDS Original Potato Chips",
      "1 lb ground beef or turkey",
      "1 packet taco seasoning",
      "2 cups shredded cheddar cheese",
      "1 cup shredded Monterey Jack cheese",
      "1 can (15 oz) black beans, drained and rinsed",
      "1 cup diced tomatoes",
      "½ cup sliced jalapeños (fresh or pickled)",
      "½ cup sour cream",
      "½ cup guacamole",
      "¼ cup sliced black olives",
      "2 green onions, thinly sliced",
      "Fresh cilantro for garnish",
      "Salsa for serving",
    ],
    directions: [
      "Preheat your oven to 375°F (190°C). Line a large baking sheet with parchment paper.",
      "In a skillet over medium heat, brown the ground beef, breaking it into small pieces. Drain excess fat.",
      "Add taco seasoning and ¼ cup water to the beef. Simmer for 5 minutes until the sauce thickens. Set aside.",
      "Arrange a generous layer of SPUDS chips on the prepared baking sheet, covering the entire surface.",
      "Sprinkle half of the cheddar and Monterey Jack cheese over the chips.",
      "Add half of the seasoned beef and black beans evenly across the chips.",
      "Add another layer of SPUDS chips, then top with remaining cheese, beef, and beans.",
      "Bake for 10-12 minutes until the cheese is melted and bubbly.",
      "Remove from oven and immediately top with diced tomatoes, jalapeños, and black olives.",
      "Add dollops of sour cream and guacamole. Garnish with green onions and fresh cilantro.",
      "Serve immediately with salsa on the side while the chips are still crispy.",
    ],
    tips: [
      "Work quickly after removing from oven to maintain chip crispiness.",
      "For vegetarian nachos, replace beef with extra black beans and corn.",
      "Try different SPUDS flavors like BBQ or Sour Cream & Onion for variety.",
      "Set up a nacho bar and let guests customize their own portions!",
    ],
    nutrition: {
      calories: 520,
      protein: "28g",
      carbs: "42g",
      fat: "26g",
      fiber: "6g",
    },
    tags: [
      "snacks",
      "party-food",
      "game-day",
      "Mexican-inspired",
      "crowd-pleaser",
    ],
    featured: false,
  },
  {
    id: 5,
    slug: "classic-french-crepes-hazelnut-chocolate",
    title: "Classic French Crepes with Hazelnut Chocolate",
    category: "Desserts",
    image: "crepes",
    cookTime: "35 min",
    prepTime: "15 min",
    totalTime: "50 min",
    servings: 6,
    difficulty: "Medium",
    rating: 4.9,
    reviews: 27,
    author: {
      name: "Smart Global Team",
      avatar: "SG",
      bio: "Professional chefs and food developers",
    },
    date: "2 months ago",
    views: 734,
    lastUpdated: "December 5, 2024",
    description:
      "Experience the authentic taste of Paris with these delicate, paper-thin crepes filled with rich hazelnut chocolate spread. Whether for breakfast, brunch, or dessert, these French classics are always a crowd favorite. The key is getting the batter consistency just right!",
    ingredients: [
      "1 cup all-purpose flour",
      "2 large eggs",
      "1½ cups whole milk",
      "2 tablespoons melted butter, plus extra for pan",
      "2 tablespoons sugar",
      "1 teaspoon vanilla extract",
      "Pinch of salt",
      "½ cup hazelnut chocolate spread (like Nutella)",
      "Sliced bananas",
      "Fresh strawberries",
      "Whipped cream",
      "Chopped hazelnuts for garnish",
      "Powdered sugar for dusting",
    ],
    directions: [
      "In a blender, combine flour, eggs, milk, melted butter, sugar, vanilla, and salt. Blend until completely smooth with no lumps.",
      "Let the batter rest in the refrigerator for at least 30 minutes (or up to overnight). This allows the flour to hydrate and creates tender crepes.",
      "Heat a non-stick 8-inch crepe pan or skillet over medium heat. Lightly brush with butter.",
      "Pour about ¼ cup of batter into the center of the pan. Immediately tilt and swirl the pan to spread the batter thinly and evenly.",
      "Cook for about 1-2 minutes until the edges begin to brown and the surface looks dry.",
      "Carefully flip the crepe using a spatula (or show off and flip it!). Cook for another 30 seconds.",
      "Transfer to a plate and cover with a kitchen towel to keep warm. Repeat with remaining batter.",
      "To serve: Spread hazelnut chocolate on one half of each crepe. Add sliced bananas or strawberries.",
      "Fold the crepe in half, then in half again to form a triangle. Alternatively, roll into cylinders.",
      "Top with whipped cream, chopped hazelnuts, and a generous dusting of powdered sugar.",
    ],
    tips: [
      "The first crepe is often a 'test' - don't worry if it's not perfect!",
      "Make sure the pan is hot enough; the batter should sizzle slightly when it hits.",
      "Stack cooked crepes with parchment paper between each to prevent sticking.",
      "Crepes freeze beautifully - make a big batch and freeze for quick breakfast treats.",
    ],
    nutrition: {
      calories: 340,
      protein: "8g",
      carbs: "44g",
      fat: "15g",
      fiber: "2g",
    },
    tags: ["dessert", "French", "crepes", "breakfast", "brunch", "chocolate"],
    featured: false,
  },
  {
    id: 6,
    slug: "premium-ice-cream-sundae",
    title: "Premium Ice Cream Sundae with Kent Toppings",
    category: "Desserts",
    image: "ice",
    cookTime: "10 min",
    prepTime: "5 min",
    totalTime: "15 min",
    servings: 2,
    difficulty: "Easy",
    rating: 4.6,
    reviews: 33,
    author: {
      name: "Smart Global Team",
      avatar: "SG",
      bio: "Professional chefs and food developers",
    },
    date: "1 week ago",
    views: 892,
    lastUpdated: "January 28, 2025",
    description:
      "Create an unforgettable ice cream experience with premium Kent Ice Cream Toppings. This sundae is all about the quality of toppings - rich chocolate sauce, sweet strawberry topping, and crunchy nuts create layers of flavor and texture that transform simple ice cream into a gourmet dessert.",
    ingredients: [
      "4-6 scoops premium vanilla ice cream",
      "Kent Chocolate Ice Cream Topping",
      "Kent Strawberry Ice Cream Topping",
      "Kent Caramel Ice Cream Topping (optional)",
      "Whipped cream",
      "2 tablespoons chopped walnuts or almonds",
      "2 tablespoons chocolate sprinkles",
      "2 maraschino cherries",
      "2 wafer cookies or pirouettes",
      "Mini chocolate chips (optional)",
    ],
    directions: [
      "Chill your sundae glasses or bowls in the freezer for 15 minutes before serving for an extra cold experience.",
      "Place 2-3 scoops of premium vanilla ice cream in each chilled glass.",
      "Drizzle generously with Kent Chocolate Topping, creating decorative swirls.",
      "Add a layer of Kent Strawberry Topping on one side for beautiful color contrast.",
      "If using caramel topping, drizzle it over the other side.",
      "Top with a large dollop of whipped cream.",
      "Sprinkle with chopped nuts and chocolate sprinkles.",
      "Place a wafer cookie or pirouette in the center standing upright.",
      "Crown with a maraschino cherry. Serve immediately with a long spoon.",
    ],
    tips: [
      "Let ice cream sit at room temperature for 2-3 minutes for easier scooping.",
      "Warm the Kent toppings slightly in the microwave for 10 seconds for a smooth drizzle.",
      "Layer different topping flavors for a 'surprise' effect with each spoonful.",
      "Make it a sundae bar party - set out all toppings and let guests build their own!",
    ],
    nutrition: {
      calories: 580,
      protein: "8g",
      carbs: "76g",
      fat: "28g",
      fiber: "2g",
    },
    tags: ["dessert", "ice-cream", "quick", "kids-friendly", "no-bake"],
    featured: false,
  },
  {
    id: 7,
    slug: "savory-breakfast-crepes-ham-cheese",
    title: "Savory Breakfast Crepes with Ham and Cheese",
    category: "Breakfast",
    image: "crepes",
    cookTime: "25 min",
    prepTime: "15 min",
    totalTime: "40 min",
    servings: 4,
    difficulty: "Medium",
    rating: 4.8,
    reviews: 19,
    author: {
      name: "Smart Global Team",
      avatar: "SG",
      bio: "Professional chefs and food developers",
    },
    date: "2 weeks ago",
    views: 445,
    lastUpdated: "January 20, 2025",
    description:
      "These elegant savory crepes are perfect for a special breakfast or brunch. Thin, delicate crepes filled with savory ham, melted Gruyere cheese, and a perfectly cooked egg create a restaurant-quality meal at home. It's like having a Parisian café breakfast in your kitchen!",
    ingredients: [
      "1 cup all-purpose flour",
      "3 large eggs (2 for batter, 1 per crepe)",
      "1¼ cups milk",
      "2 tablespoons melted butter",
      "½ teaspoon salt",
      "¼ teaspoon black pepper",
      "8 thin slices of ham or turkey",
      "1 cup shredded Gruyere or Swiss cheese",
      "Fresh baby spinach leaves",
      "Cherry tomatoes, halved",
      "Fresh chives, chopped",
      "Dijon mustard (optional)",
      "Butter for cooking",
    ],
    directions: [
      "Make the crepe batter: Blend flour, 2 eggs, milk, melted butter, salt, and pepper until smooth. Refrigerate for 20 minutes.",
      "Heat an 8-inch non-stick pan over medium heat. Lightly butter the pan.",
      "Pour ¼ cup batter into the pan, swirling immediately to coat the bottom thinly.",
      "Cook for 1-2 minutes until lightly golden. Flip and cook 30 seconds more. Set aside and keep warm.",
      "For the filling: In the same pan, place a cooked crepe back in. Arrange 2 slices of ham in the center.",
      "Sprinkle with shredded cheese and add a handful of fresh spinach.",
      "Crack an egg in the center. Cover the pan with a lid and cook for 3-4 minutes until the egg white is set but yolk remains runny.",
      "Fold the four edges of the crepe toward the center, creating a square pocket around the filling.",
      "Carefully slide onto a plate. Garnish with cherry tomatoes, chives, and a crack of black pepper.",
      "Serve immediately while the cheese is melted and egg is warm. Add a side of Dijon mustard if desired.",
    ],
    tips: [
      "For a vegetarian version, replace ham with sautéed mushrooms.",
      "Make crepes ahead and store in the fridge for up to 2 days.",
      "Use a clear lid when cooking the egg so you can watch it without lifting the lid.",
      "Adjust cooking time based on how runny you like your egg yolk.",
    ],
    nutrition: {
      calories: 420,
      protein: "24g",
      carbs: "28g",
      fat: "22g",
      fiber: "1g",
    },
    tags: ["breakfast", "savory", "brunch", "crepes", "eggs", "French"],
    featured: false,
  },
  {
    id: 8,
    slug: "spuds-chips-fish-tacos",
    title: "Crispy SPUDS Fish Tacos with Lime Crema",
    category: "Main Course",
    image: "spuds",
    cookTime: "30 min",
    prepTime: "20 min",
    totalTime: "50 min",
    servings: 4,
    difficulty: "Medium",
    rating: 4.9,
    reviews: 38,
    author: {
      name: "Smart Global Team",
      avatar: "SG",
      bio: "Professional chefs and food developers",
    },
    date: "1 month ago",
    views: 521,
    lastUpdated: "January 5, 2025",
    description:
      "Take taco night to the next level! We've created an innovative recipe that uses crushed SPUDS chips as a crunchy coating for tender fish fillets. Combined with fresh cabbage slaw and tangy lime crema, these tacos are crispy, zesty, and absolutely addictive.",
    ingredients: [
      "1 lb white fish fillets (cod, tilapia, or halibut)",
      "2 cups SPUDS Original Chips, finely crushed",
      "½ cup all-purpose flour",
      "2 eggs, beaten",
      "8 small corn or flour tortillas",
      "2 cups shredded purple cabbage",
      "1 cup shredded green cabbage",
      "½ cup sour cream",
      "2 tablespoons lime juice",
      "1 teaspoon lime zest",
      "½ teaspoon cumin",
      "Salt and pepper to taste",
      "Fresh cilantro",
      "Sliced avocado",
      "Hot sauce (optional)",
      "Lime wedges for serving",
    ],
    directions: [
      "Prepare the lime crema: Mix sour cream, lime juice, lime zest, cumin, salt, and pepper. Refrigerate until needed.",
      "Make the slaw: Combine purple and green cabbage in a bowl. Toss with 2 tablespoons of the lime crema. Set aside.",
      "Cut fish fillets into taco-sized portions (about 3-4 inches long). Pat dry and season with salt and pepper.",
      "Set up breading station: Place flour in one shallow dish, beaten eggs in another, and crushed SPUDS chips in a third.",
      "Coat each fish piece: First in flour (shake off excess), then egg, then press firmly into crushed SPUDS chips to coat completely.",
      "Heat ½ inch of oil in a large skillet over medium-high heat to 350°F.",
      "Carefully place coated fish in hot oil. Fry for 3-4 minutes per side until golden brown and crispy. Don't overcrowd the pan.",
      "Transfer to a paper towel-lined plate to drain. Keep warm in a 200°F oven while finishing the batch.",
      "Warm tortillas in a dry skillet or directly over a gas flame for 30 seconds per side.",
      "Assemble tacos: Place crispy fish on each tortilla, top with cabbage slaw, drizzle with lime crema, and garnish with cilantro and avocado.",
      "Serve with lime wedges and hot sauce on the side.",
    ],
    tips: [
      "Use a food processor to crush SPUDS chips evenly - they should resemble coarse breadcrumbs.",
      "Keep one hand 'dry' and one 'wet' when breading to avoid clumpy fingers.",
      "The oil is ready when a chip sizzles immediately when dropped in.",
      "For meal prep, bread the fish ahead and refrigerate until ready to fry.",
    ],
    nutrition: {
      calories: 485,
      protein: "32g",
      carbs: "48g",
      fat: "18g",
      fiber: "5g",
    },
    tags: ["main-course", "fish", "tacos", "Mexican", "crispy", "dinner"],
    featured: true,
  },
  {
    id: 9,
    slug: "kent-boringer-birthday-cake-pancakes",
    title: "Kent Boringer Birthday Cake Pancakes",
    category: "Breakfast",
    image: "top2",
    cookTime: "20 min",
    prepTime: "10 min",
    totalTime: "30 min",
    servings: 4,
    difficulty: "Easy",
    rating: 5.0,
    reviews: 52,
    author: {
      name: "Smart Global Team",
      avatar: "SG",
      bio: "Professional chefs and food developers",
    },
    date: "3 days ago",
    views: 1203,
    lastUpdated: "February 1, 2025",
    description:
      "Make any morning feel like a celebration with these festive birthday cake pancakes! Made with Kent Boringer mix and topped with vanilla frosting and rainbow sprinkles, these pancakes taste exactly like birthday cake. Perfect for birthday breakfasts, celebrations, or when you just want breakfast to feel extra special.",
    ingredients: [
      "2 cups Kent Boringer Pancake Mix",
      "1½ cups milk",
      "2 eggs",
      "3 tablespoons melted butter",
      "1 teaspoon vanilla extract",
      "½ teaspoon almond extract",
      "⅓ cup rainbow sprinkles, plus extra for topping",
      "4 oz cream cheese, softened",
      "2 tablespoons butter, softened",
      "1 cup powdered sugar",
      "2 tablespoons milk",
      "½ teaspoon vanilla extract",
      "Pink or blue food coloring (optional)",
      "Whipped cream for serving",
    ],
    directions: [
      "Make the vanilla frosting: Beat softened cream cheese and butter until fluffy. Gradually add powdered sugar, then milk and vanilla. Add food coloring if desired. Refrigerate.",
      "In a large bowl, mix Kent Boringer Pancake Mix with milk, eggs, melted butter, vanilla, and almond extract until just combined.",
      "Gently fold in ⅓ cup rainbow sprinkles. Be careful not to overmix or the colors will bleed.",
      "Heat a griddle or non-stick pan over medium heat. Grease lightly with butter.",
      "Pour ¼ cup batter per pancake. Cook until bubbles form and edges are set, about 2-3 minutes.",
      "Flip and cook another 1-2 minutes until golden brown.",
      "Stack 3-4 pancakes per serving on plates.",
      "Spread vanilla frosting between layers and on top (or serve it on the side).",
      "Top with whipped cream and a generous amount of rainbow sprinkles.",
      "For the full birthday experience, add a candle on top!",
    ],
    tips: [
      "Use gel food coloring instead of liquid to avoid thinning the frosting.",
      "Make frosting the night before to save time on busy mornings.",
      "Freeze leftover pancakes without frosting - they reheat beautifully in the toaster.",
      "Try different extracts like coconut or lemon for flavor variations.",
    ],
    nutrition: {
      calories: 520,
      protein: "10g",
      carbs: "68g",
      fat: "24g",
      fiber: "1g",
    },
    tags: [
      "breakfast",
      "birthday",
      "celebration",
      "kids-favorite",
      "fun",
      "pancakes",
    ],
    featured: true,
  },
  {
    id: 10,
    slug: "loaded-spuds-breakfast-skillet",
    title: "Loaded SPUDS Breakfast Skillet",
    category: "Breakfast",
    image: "spuds",
    cookTime: "25 min",
    prepTime: "10 min",
    totalTime: "35 min",
    servings: 4,
    difficulty: "Easy",
    rating: 4.7,
    reviews: 29,
    author: {
      name: "Smart Global Team",
      avatar: "SG",
      bio: "Professional chefs and food developers",
    },
    date: "1 week ago",
    views: 678,
    lastUpdated: "January 28, 2025",
    description:
      "Start your day with this hearty, crowd-pleasing breakfast skillet! Crispy SPUDS chips form the base for scrambled eggs, crumbled breakfast sausage, melted cheese, and all your favorite breakfast toppings. It's like combining hash browns, eggs, and chips into one incredible dish.",
    ingredients: [
      "1 large bag SPUDS Original Chips",
      "8 large eggs",
      "¼ cup milk",
      "1 lb breakfast sausage",
      "1 red bell pepper, diced",
      "½ onion, diced",
      "1½ cups shredded cheddar cheese",
      "¼ cup chopped green onions",
      "½ cup sour cream",
      "1 avocado, sliced",
      "Fresh salsa",
      "Salt and black pepper to taste",
      "Hot sauce (optional)",
      "Fresh cilantro for garnish",
    ],
    directions: [
      "Preheat oven to 375°F (190°C).",
      "In a large oven-safe skillet over medium heat, cook breakfast sausage until browned and crumbly. Remove and set aside, leaving drippings in pan.",
      "In the same skillet, sauté diced bell pepper and onion until softened, about 5 minutes.",
      "While vegetables cook, whisk eggs with milk, salt, and pepper in a bowl.",
      "Spread SPUDS chips evenly across the bottom of the skillet, covering the vegetables.",
      "Pour whisked eggs over the chips and vegetables. Sprinkle cooked sausage on top.",
      "Let cook undisturbed for 2-3 minutes on the stovetop until edges begin to set.",
      "Sprinkle shredded cheddar cheese evenly over the top.",
      "Transfer the skillet to the preheated oven. Bake for 12-15 minutes until eggs are fully set and cheese is melted and bubbly.",
      "Remove from oven and let cool for 2-3 minutes.",
      "Top with green onions, dollops of sour cream, sliced avocado, and fresh salsa.",
      "Garnish with cilantro and serve hot, directly from the skillet. Add hot sauce to taste.",
    ],
    tips: [
      "Make it vegetarian by swapping sausage for black beans and extra veggies.",
      "Use different cheese varieties like Monterey Jack or pepper jack for variety.",
      "This recipe is perfect for meal prep - reheat portions throughout the week.",
      "Add jalapeños for a spicy kick!",
    ],
    nutrition: {
      calories: 645,
      protein: "34g",
      carbs: "38g",
      fat: "40g",
      fiber: "4g",
    },
    tags: ["breakfast", "brunch", "skillet", "one-pan", "hearty", "weekend"],
    featured: false,
  },
];

// Related recipes suggestions - for the detail page
export const getRelatedRecipes = (
  currentRecipeId,
  currentCategory,
  limit = 3,
) => {
  return recipesData
    .filter(
      (recipe) =>
        recipe.id !== currentRecipeId && recipe.category === currentCategory,
    )
    .slice(0, limit);
};

// Filter recipes by category
export const getRecipesByCategory = (category) => {
  if (category === "All") return recipesData;
  return recipesData.filter((recipe) => recipe.category === category);
};

// Get recipe by slug
export const getRecipeBySlug = (slug) => {
  return recipesData.find((recipe) => recipe.slug === slug);
};

// Get featured recipes
export const getFeaturedRecipes = () => {
  return recipesData.filter((recipe) => recipe.featured);
};
